name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pylint

      - name: Run tests with coverage
        run: |
          pytest --cov=app tests/
          coverage report --fail-under=100

      - name: Run pylint
        run: |
          pylint app/ tests/ --fail-under=10

  deploy:
    runs-on: self-hosted
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env
      
    - name: Update and restart application
      run: |
        docker-compose -f docker-compose.prod.yml down
        docker-compose -f docker-compose.prod.yml up -d --build


    - name: Clean up
      run: docker system prune -f
