name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env
      
    - name: Update and restart application
      run: |
        docker-compose -f docker-compose.prod.yml down
        docker-compose -f docker-compose.prod.yml up -d --build


    - name: Clean up
      run: docker system prune -f
