name: FastAPI CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Update and restart application
      run: |
        git pull origin main
        docker-compose down
        docker-compose up -d --build

    - name: Clean up
      run: docker system prune -f
